[window]
opacity = 0.9
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 6
y = 0

[keyboard]
bindings = [
	{key = "+", mods = "Control", action = "IncreaseFontSize"},
	{key = "-", mods = "Control", action = "DecreaseFontSize"},
	{key = "n", mods = "Control", action = "CreateNewWindow"},
	{key = "e", mods = "Control", action = "Quit"}
]

[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x282828"
